---
galaxy_info:
  author: Ansible Playbook
  description: Docker and Docker Compose installation role
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - docker-compose
    - container

dependencies: [] 